### ISSUE TITLE
The recent gzip behaviour

### ISSUE THREAD

**Issue by KidkArolis** [npm/public-api#18]
Hi,

Not sure this is the right place to report this, I can post somewhere else if more appropriate.

We've noticed some new type of failures today in some our internal systems that were fetching metadata and packages from https://registry.npmjs.org.

We're using `request` package to make requests to the registry. Turns out that if you don't explicitly opt into `gzip: true` flag, request lib does not send `'accept-encoding': 'gzip'` and does not try to ungzip the response. Now this used to work fine and we didn't have any issues for a while.

But starting today morning (~8AM UTC) we've noticed that npm was responding with gzipped content and our parsing of package metadata started failing. That's because even though we are not sending `'accept-encoding': 'gzip'` header, npm registry responds with gzipped content anyway. This was happening only sometimes and only for some packages (e.g. lodash, pako, hashids).

So all in all, we've now setting `gzip: true` and are always ready to handle gzipped content. But this  tripped us up and might trip up other people and software. Perhaps you should consider respecting the `accept-encoding: gzip` header or rather it's absence. I'm not even sure what the spec on this is. Feel free to close.

**Comment by terinjokes** [comment]
> This was happening only sometimes and only for some packages (e.g. lodash, pako, hashids).

Outside looking in, but this sounds to me as if "Accept-Encoding" is no longer considered part of the cache key.

**Comment by othiym23** [comment]
Oh hai there, @terinjokes! I didn't even see this issue here. I redirect the both of you over to https://github.com/npm/npm/issues/12196#issuecomment-206525005, where I discuss what happened and how this is being resolved. In the near future, we should have an issue-tracking repo up at npm/registry, which will be a much better forum for discussing operational issues with the registry. Thanks for your time! Ta!
